# Site
title:              TsaiTsai
bio:                '部落客日記'
description:        "分享生活、旅遊記事，把握現在的日子留做以後懷念。"
locale:             en_US
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://TsaiTsai2000.github.io" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           "https://www.facebook.com/wl03078162"
instagram:          "https://www.instagram.com/sincih0822/"
github:             default

# personal
location:           Taoyuan, R.O.C.
phone:              Please contact me by mail.
email:              wl03078162@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
